I committed some lines I didn't mean to to the runme.py file! Please undo my mistakes.

